export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_LIST_FAIL = 'PRODUCTS_LIST_FAIL'

export const PRODUCT_GENRES_REQUEST = 'PRODUCT_GENRES_REQUEST'
export const PRODUCTS_GENRES_SUCCESS = 'PRODUCTS_GENRES_SUCCESS'
export const PRODUCTS_GENRES_FAIL = 'PRODUCTS_GENRES_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCTS_DETAILS_SUCCESS = 'PRODUCTS_DETAILS_SUCCESS'
export const PRODUCTS_DETAILS_FAIL = 'PRODUCTS_DETAILS_FAIL'
export const PRODUCTS_DETAILS_CLEAR = 'PRODUCTS_DETAILS_CLEAR'