const products = [
  {
    '_id': '1',
    'name': 'Putins People',
    'image': '/images/Putins People.jpg',
    'description':
      'THE SUNDAY TIMES BESTSELLER, An outstanding expose of Putin and his criminal pals',
    'author': 'Catherine Belton',
	'publisher': 'Pan Macmillan',
	'isbn': '9781529033793',
    'category': 'Biography',
	'language': 'English',
    'price': 89.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Crying in H Mart',
    'image': '/images/Crying in H Mart.jpg',
    'description':
      'The New York Times bestseller from the Grammy-nominated indie rockstar Japanese Breakfast, an unflinching, deeply moving memoir about growing up mixed-race, Korean food, losing her Korean mother, and forging her own identity in the wake of her loss, which brought her to reclaim the gifts of taste, language, and history her mother had given her.',
    'author': 'Michelle Zauner',
	'publisher': 'Pan Macmillan',
	'isbn': '9781529033233',
    'category': 'Biography',
	'language': 'English',
    'price': 59.99,
    'countInStock': 0,
    'rating': 4.3,
    'numReviews': 12,
  },
  {
    '_id': '3',
    'name': 'This is Going to Hurt',
    'image': '/images/This is Going to Hurt.jpg',
    'description':
      'Now A Major BBC Series Starring Ben Whishaw.',
    'author': 'Adam Kay',
	'publisher': 'Pan Macmillan',
	'isbn': '9781509858637',
    'category': 'Biography',
	'language': 'English',
    'price': 79.99,
    'countInStock': 56,
    'rating': 4.3,
    'numReviews': 120,
  },
  {
    '_id': '4',
    'name': 'Critical',
    'image': '/images/Critical.jpg',
    'description':
      'A very special book filled with stories of survival, hope and loss.',
    'author': 'Dr Matt Morgan',
	'publisher': 'Simon & Schuster Ltd',
	'isbn': '9781471173035',
    'category': 'Biography',
	'language': 'English',
    'price': 95.99,
    'countInStock': 56,
    'rating': 3.3,
    'numReviews': 20,
  },
  {
    '_id': '5',
    'name': 'A Lick and a Promise',
    'image': '/images/A Lick and a Promise.jpg',
    'description':
      'A Lick and a Promise is the debut poetry collection of one of Irelands most famed female musicians, Imelda May.',
    'author': 'Imelda May',
	'publisher': 'Faber Music Ltd',
	'isbn': '9780571542390',
    'category': 'Biography',
	'language': 'English',
    'price': 95.99,
    'countInStock': 56,
    'rating': 4.7,
    'numReviews': 78,
  },
  {
    '_id': '6',
    'name': 'Just Kids',
    'image': '/images/Just Kids.jpg',
    'description':
      'Winner of the 2010 Non-Fiction National Book Award Patti Smiths definitive memoir: an evocative, honest and moving coming-of-age story of her extraordinary relationship with the artist Robert Mapplethorpe',
    'author': 'Patti Smith',
	'publisher': 'Bloomsbury Publishing Plc',
	'isbn': '9780747568766',
    'category': 'Biography',
	'language': 'English',
    'price': 105.99,
    'countInStock': 19,
    'rating': 4.7,
    'numReviews': 78,
  },
    {
        '_id': '7',
        'name': 'Berserk Deluxe Volume 3',
        'image': '/images/Berserk Deluxe Volume 3.jpg',
        'description':
            'The hundred-year war between the kingdoms of Midland and Tudor nears an end as the legendary Band of the Hawk mercenaries, led by the charismatic Griffith and his fearless berserker champion Guts, turn the tide in Midland s favor. But impending victory ignites a secret war within Midland, as those seeking courtly favor see the ambitious Griffith as an obstacle to power. And nothing is more powerful than an enemy unseen! Collects Berserk volumes 7-9.\n' +
            '\n' +
            'Berserk Deluxe Volume 3 Hardback edition by Kentaro Miura',
        'author': 'Kentaro Miura',
        'publisher': 'Dark Horse Comics,U.S.',
        'isbn': '9781506712000',
        'category': 'Manga',
        'language': 'English',
        'price': 499.99,
        'countInStock': 2,
        'rating': 5,
        'numReviews': 256,
    },
  {
    '_id': '8',
    'name': 'No Longer Human',
    'image': '/images/No Longer Human.jpg',
    'description':
        'Plagued by a maddening anxiety ? the terrible disconnect between his own concept of happiness and the joy of the rest of the world ? Yozo Oba plays the clown in his dissolute life, holding up a mask for those around him as he spirals ever downward, locked arm-in-arm with death. 30,000 first printing.\n' +
        '\n' +
        'No Longer Human Hardback edition by Junji Ito',
    'author': 'Junji Ito',
    'publisher': 'Dark Horse Comics,U.S.',
    'isbn': '9781974707096',
    'category': 'Manga',
    'language': 'English',
    'price': 299.99,
    'countInStock': 13,
    'rating': 3.2,
    'numReviews': 58,
  },
]


export default products
