const products = [
  {
    '_id': '1',
    'name': 'Putins People',
    'image': '/images/Putins People.jpg',
    'description':
      'THE SUNDAY TIMES BESTSELLER, An outstanding expose of Putin and his criminal pals',
    'author': 'Catherine Belton',
	'publisher': 'Pan Macmillan',
	'isbn': '9781529033793',
    'category': 'Biography',
	'language': 'English',
    'price': 89.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Crying in H Mart',
    'image': '/images/Crying in H Mart.jpg',
    'description':
      'The New York Times bestseller from the Grammy-nominated indie rockstar Japanese Breakfast, an unflinching, deeply moving memoir about growing up mixed-race, Korean food, losing her Korean mother, and forging her own identity in the wake of her loss, which brought her to reclaim the gifts of taste, language, and history her mother had given her.',
    'author': 'Michelle Zauner',
	'publisher': 'Pan Macmillan',
	'isbn': '9781529033233',
    'category': 'Biography',
	'language': 'English',
    'price': 59.99,
    'countInStock': 27,
    'rating': 4.3,
    'numReviews': 12,
  },
  {
    '_id': '3',
    'name': 'This is Going to Hurt',
    'image': '/images/This is Going to Hurt.jpg',
    'description':
      'Now A Major BBC Series Starring Ben Whishaw.',
    'author': 'Adam Kay',
	'publisher': 'Pan Macmillan',
	'isbn': '9781509858637',
    'category': 'Biography',
	'language': 'English',
    'price': 79.99,
    'countInStock': 56,
    'rating': 4.3,
    'numReviews': 120,
  },
  {
    '_id': '4',
    'name': 'Critical',
    'image': '/images/Critical.jpg',
    'description':
      'A very special book filled with stories of survival, hope and loss.',
    'author': 'Dr Matt Morgan',
	'publisher': 'Simon & Schuster Ltd',
	'isbn': '9781471173035',
    'category': 'Biography',
	'language': 'English',
    'price': 95.99,
    'countInStock': 56,
    'rating': 3.3,
    'numReviews': 20,
  },
  {
    '_id': '5',
    'name': 'A Lick and a Promise',
    'image': '/images/A Lick and a Promise.jpg',
    'description':
      'A Lick and a Promise is the debut poetry collection of one of Irelands most famed female musicians, Imelda May.',
    'author': 'Imelda May',
	'publisher': 'Faber Music Ltd',
	'isbn': '9780571542390',
    'category': 'Biography',
	'language': 'English',
    'price': 95.99,
    'countInStock': 56,
    'rating': 4.7,
    'numReviews': 78,
  },
  {
    '_id': '6',
    'name': 'Just Kids',
    'image': '/images/Just Kids.jpg',
    'description':
      'Winner of the 2010 Non-Fiction National Book Award Patti Smiths definitive memoir: an evocative, honest and moving coming-of-age story of her extraordinary relationship with the artist Robert Mapplethorpe',
    'author': 'Patti Smith',
	'publisher': 'Bloomsbury Publishing Plc',
	'isbn': '9780747568766',
    'category': 'Biography',
	'language': 'English',
    'price': 105.99,
    'countInStock': 19,
    'rating': 4.7,
    'numReviews': 78,
  },
]


export default products
